import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";

import "./globals.css"
import Config from "@/config";
import CoreMenu from "@/components/Menu/CoreMenu";
import SidebarCore from "@/components/Sidebar/SidebarCore";
import ChatCore from "@/components/Chat/ChatCore";

export const kodchasan = Kodchasan({
  subsets: ["latin"],
  weight: ["200", "300", "500", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kodchasan.className} bg-dark w-full flex flex-wrap`}>
        <section className="w-full h-screen flex flex-wrap">
          <section className="w-full h-auto">
            <CoreMenu></CoreMenu>
          </section>

          <section
            className="h-full"
            style={{
              width: `${Config.App.Info.SidebarSize}%`
            }}
          >
            <SidebarCore></SidebarCore>
          </section>

          <section
            className="h-full"
            style={{
              width: `${100 - (Config.App.Info.SidebarSize + Config.App.Info.ChatSize)}%`
            }}
          >
            {children}
          </section>

          <section
            className="h-full"
            style={{
              width: `${Config.App.Info.ChatSize}%`
            }}
          >
            <ChatCore></ChatCore>
          </section>
        </section>
      </body>
    </html>
  );
}
